[package]
name = "pilier-runtime"
version = "0.1.0"
description = "The state transition function of the Pilier Blockchain."
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
frame-try-runtime = { workspace = true, optional = true }

# Сериализация (Base)
codec = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

frame-benchmarking = { workspace = true, optional = true } 
frame-system-benchmarking = { workspace = true, optional = true }

# Ядро FRAME
frame-support = { features = ["experimental"], workspace = true }
frame-system.workspace = true
frame-executive.workspace = true
frame-metadata-hash-extension.workspace = true

# Паллеты (Только то, что нужно для Pilier PoA)
pallet-aura.workspace = true
pallet-balances.workspace = true
pallet-grandpa.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
pallet-transaction-payment.workspace = true

# Примитивы (sp-*)
sp-api.workspace = true
sp-block-builder.workspace = true
sp-consensus-aura = { features = ["serde"], workspace = true }
sp-consensus-grandpa = { features = ["serde"], workspace = true }
sp-core = { features = ["serde"], workspace = true }
sp-inherents.workspace = true
sp-offchain.workspace = true
sp-runtime = { features = ["serde"], workspace = true }
sp-session.workspace = true
sp-storage.workspace = true
sp-transaction-pool.workspace = true
sp-version = { features = ["serde"], workspace = true }
sp-genesis-builder.workspace = true
sp-io.workspace = true

# RPC Runtime APIs
frame-system-rpc-runtime-api.workspace = true
pallet-transaction-payment-rpc-runtime-api.workspace = true

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-executive/std",
  "frame-benchmarking/std", 
  "frame-system-benchmarking/std",
  "frame-metadata-hash-extension/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "scale-info/std",
  "serde_json/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-consensus-grandpa/std",
  "sp-core/std",
  "sp-genesis-builder/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-storage/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "sp-io/std",
  "substrate-wasm-builder",
  "frame-try-runtime?/std",
]

# Включаем для генерации хэша метаданных (нужно для Ledger/Safe)
metadata-hash = ["substrate-wasm-builder/metadata-hash"]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]