[package]
name = "pilier-node"
description = "The Pilier Blockchain node implementation."
version = "0.1.0"
license = "Apache-2.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# CLI & Async
clap = { features = ["derive"], workspace = true }
futures = { features = ["thread-pool"], workspace = true }
serde_json = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }

# Pilier Runtime (Связка с нашим рантаймом)
pilier-runtime = { workspace = true }

# Substrate Client Stack (sc-*)
sc-cli = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-service = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-offchain = { workspace = true }
sc-consensus = { workspace = true }
sc-consensus-aura = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-client-api = { workspace = true }
sc-basic-authorship = { workspace = true }

# Substrate Primitives (sp-*)
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }
sp-timestamp = { workspace = true }
sp-inherents = { workspace = true }
sp-keyring = { workspace = true }
sp-blockchain = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-genesis-builder = { workspace = true }

# FRAME & Pallets
frame-system = { workspace = true }
frame-metadata-hash-extension = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
frame-benchmarking-cli = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
default = ["std"]
std = ["pilier-runtime/std"]

runtime-benchmarks = [
  "frame-benchmarking-cli/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-transaction-payment/runtime-benchmarks",
  "sc-service/runtime-benchmarks",
  "pilier-runtime/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]

try-runtime = [
  "frame-system/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "pilier-runtime/try-runtime",
  "sp-runtime/try-runtime",
]